#!/usr/bin/env php
<?php

/**
 * This file is part of CodeIgniter 4 framework.
 *
 * (c) CodeIgniter Foundation <admin@codeigniter.com>
 *
 * For the full copyright and license information, please view
 * the LICENSE file that was distributed with this source code.
 */

use CodeIgniter\Boot;
use Config\Paths;

// Periksa server API - tidak mendukung php-cgi
if (str_starts_with(PHP_SAPI, 'cgi')) {
    exit("The cli tool is not supported when running php-cgi. It needs php-cli to function!\n\n");
}

// Periksa versi PHP yang dibutuhkan
$minPhpVersion = '8.1';
if (version_compare(PHP_VERSION, $minPhpVersion, '<')) {
    $message = sprintf(
        'Your PHP version must be %s or higher to run CodeIgniter. Current version: %s',
        $minPhpVersion,
        PHP_VERSION,
    );

    exit($message);
}

// Tampilkan error saat menggunakan CLI
error_reporting(E_ALL);
ini_set('display_errors', '1');

// Set path ke front controller
define('FCPATH', __DIR__ . DIRECTORY_SEPARATOR . 'public' . DIRECTORY_SEPARATOR);

// Pastikan direktori saat ini mengarah ke direktori front controller
chdir(FCPATH);

// Load konfigurasi path
require FCPATH . '../app/Config/Paths.php';

$paths = new Paths();

// Load bootstrap framework
require $paths->systemDirectory . '/Boot.php';

exit(Boot::bootSpark($paths));
